/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const IconMaterialSymbolsArrowBack: typeof import('~icons/material-symbols/arrow-back.jsx')['default']
  const IconMaterialSymbolsArrowForward: typeof import('~icons/material-symbols/arrow-forward.jsx')['default']
  const IconMaterialSymbolsLock: typeof import('~icons/material-symbols/lock.jsx')['default']
}
