/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const IconMaterialSymbolsArrowDropDown: typeof import('~icons/material-symbols/arrow-drop-down.jsx')['default']
  const IconMaterialSymbolsArrowDropUp: typeof import('~icons/material-symbols/arrow-drop-up.jsx')['default']
}
